### ISSUE TITLE
Where is the configuration file to set server and port information

### ISSUE THREAD

**Issue by lonnietc** [dgraph-io/website#7]
Greetings,

I have set up the Dgraph cluster for testing as well as have loaded the benchmark data for the film/movie/actor series. I have also set up the "website" web server code which seems to serve well,

what I need to locate is where is the configuration file in the "website" repository to set up the server IP and port to call the Dgraph cluster?

Any help would be greatly appreciated.

Cheers,
Lonnie

**Comment by pawanrawal** [comment]
Hey @lonnietc 

The configuration file that you are looking for is the `nginx.conf`. You will have to modify the `nginx.conf` slightly to run this locally. Instructions for what modifications are to be made are in the `README.md` of this repository. You could then use docker to run the website if you desire. Let me know if you face any other problems while running it?
