### ISSUE TITLE
Why is 'website' so dependent upon googleapis.com?

### ISSUE THREAD

**Issue by lonnietc** [dgraph-io/website#8]
Hello,

I am searching for the configuration files for 'website' app so that I can get it talking to my dgraph cluster, but looking though all of the files, I cannot find the parameters, but did notice some query functions that seem to be dependent upon calls to googleapis.com and I do not see the reason for this.

Can some one please clarify what is happening here and why?

Thanks,
Lonnie

**Comment by pawanrawal** [comment]
We use googleapis to get `xid` from the query string for the freebase data. Hope that resolves this for you.
